source "https://rubygems.org"

# Declare your gem's dependencies in redhat_access.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem 'jquery-rails'
gem 'haml-rails'
gem 'uglifier'
gem 'therubyracer'
gem 'sass-rails'
gem 'angular-rails-templates', ">=0.0.4", '<0.1.4'
#gem 'angular-rails-templates', "=0.0.4"
#gem 'redhat_access_lib'


# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
